name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  Practice:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show what's in the directory
      run: |
        ls
    - name: Show what all is in the parent directory
      run: |
        cd ..
        ls
        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        ls
        nuget restore CitizensAdvice.sln
        echo Nuget Restored
        cd CitizensAdvice
        cd CitizensAdvice.Android
        echo Switched directory to CitizensAdvice.Android
        msbuild CitizensAdvice.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        nuget restore CitizensAdvice.sln
        cd CitizensAdvice
        msbuild CitizensAdvice.iOS/CitizensAdvice.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
        
  build:
    name: Build APK
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Building APK
        uses: ./action
        with:
          args: /r:True /t:SignAndroidPackage /p:AndroidSdkDirectory=/android/sdk CitizensAdvice/CitizensAdvice.Android.csproj
      - name: Artifacts
        run: |
          mkdir -p apks
          cp CitizensAdvice/CitizensAdvice.Android/bin/Debug/*.apk apks
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: apks
          path: apks
